version: '3'

services:
  web:
    image: dnhandy/cumulus_web
    depends_on:
      - worker
    ports:
      - 80:80
    restart: always

  api:
    image: dnhandy/cumulus_api
    depends_on:
      - redis

    environment:
      - RAILS_ENV=production
      - SECRET_KEY_BASE=857ee5594b934c60900bc0f965f1b809b7f7ef0f8fa6f3a71d558d4b1e72c4e71e8dc6ceb15ee5686bed9afd522ff49e8b17ada9df9b31203dc46690962ea5bc
      - HOSTNAME=localhost/api
    restart: always

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=cumulus
      - POSTGRES_PASSWORD=cumulus
      - PGDATA=/data
    volumes:
      - ~/data/cumulus:/data
    restart: always

  redis:
    image: redis:alpine
    depends_on:
      - db
    restart: always

  worker:
    image: dnhandy/cumulus_worker
    depends_on:
      - api
    environment:
      - RAILS_ENV=production
      - SIDEKIQ_WORKERS=1
    restart: always
