FROM ruby:alpine

RUN apk add --update ruby-dev build-base postgresql-client postgresql-dev sqlite-dev python3
RUN gem install bundler

COPY server/Gemfile /tmp/
WORKDIR /tmp
RUN bundle update && bundle install

RUN mkdir -p "`python3 -m site --user-site`"
ADD modules/python/cumulus.py /tmp
RUN mv /tmp/cumulus.py "`python3 -m site --user-site`"

ENV app /app
RUN mkdir $app
WORKDIR $app
ADD server/ $app

CMD bundle exec sidekiq
